:content = application/json
:host = http://localhost:8080
# Root

GET :host/api
Accept: :content
Content-Type: :content

# Signin
POST :host/api/signin
Accept: :content
Content-Type: :content
{
    "name": "Vitalii",
    "second_name": "Drevenchuk",
    "email": "example@post.com",
    "password": "pass"
}

#{"token":"c1148d4b-f671-4598-a318-1958785d0260"}


:token = c1148d4b-f671-4598-a318-1958785d0260

# Login

POST :host/api/login
Accept: :content
Content-Type: :content
{
    "email": "example@post.com",
    "password": "pass"
}

# List users
GET :host/api/users
Accept: :content

#
:user_id=example@post.com
# User
GET :host/api/users/:user_id
Accept: :content

# List rooms
GET :host/api/rooms
Accept: :content

# Add room
POST :host/api/rooms
Accept: :content
Content-Type: :content
{
    "name": "room 1",
    "users": [
        {
            "id": "example@post.com"
        }
    ]
}

#
:room_id=room 1
# Room
GET :host/api/rooms/:room_id
Accept: :content
