:content = application/json
:host = http://localhost:8080

:auth = Authorization:

# Signin
POST :host/api/auth/signin
Accept: :content
Content-Type: :content
{
    "nick": "example@post.com",
    "name": "test",
    "second_name": "Second",
    "password": "pass"
}

# Login

POST :host/api/auth/login
Accept: :content
Content-Type: :content
{
    "nick": "example@post.com",
    "password": "pass"
}

:token = ZXhhbXBsZUBwb3N0LmNvbTpwYXNz
:authToken = :auth Basic :token

# List users
GET :host/api/users
Accept: :content
:authToken
#[
#  {"id":"examplew@post.com","email":"examplew@post.com","name":"Name","second_name":"Second"}]

#
:user_id=example@post.com
# User
GET :host/api/users/:user_id
Accept: :content
:authToken

# List rooms
GET :host/api/rooms
Accept: :content
:authToken

# Add room
POST :host/api/rooms
Accept: :content
Content-Type: :content
:authToken

{
    "name": "test"
}

#
:room_id=test
# Room
GET :host/api/rooms/:room_id
Accept: :content
:authToken
