version: '3'


# global environmental variables
env:
  DEBUG: 1

tasks:
  default:
    deps: [build, test]
    desc: Builds and tests all components

  help:
    cmds:
      - cmd: "go-task --list"
        silent: true


  # # run this task before each other task

  # build tasks
  build:
    desc: Builds the backend
    cmds:
      - cmd: echo "Building ..."
        silent: true
      - task: build_sqlite
      - task: build_memory
      - task: build_client

  build_sqlite:
    desc: Builds sqlite server
    cmds:
      - cmd: echo "Build sqlite server"
        silent: true
      - cmd: go build -o ./bin/sqlite ./cmd/sqlite/sqlite_server.go

  build_memory:
    desc: Builds memory server
    cmds:
      - cmd: echo "Build memory server"
        silent: true
      - cmd: go build -o ./bin/memory ./cmd/memory/memory_server.go

  build_client:
    desc: Builds client
    cmds:
      - cmd: echo "Build client"
        silent: true
      - cmd: go build -o ./bin/client ./cmd/client.go

  # test tasks
  test:
    desc: Tests project
    cmds:
      - cmd: echo "Testing project"
        silent: true
      - cmd: go test -p 1 -count=1 -cover -coverprofile=unit.coverage.out ./...

  start_memory:
    desc: Starts memory server
    cmds:
      - cmd: echo "Starting memory server"
        silent: true
      - task: build_memory
      - cmd: ./bin/memory

  start_sqlite:
    desc: Starts sqlite server
    env:
      MIGRATIONS:
        sh: echo "$(pwd)/migrations"
    cmds:
      - cmd: echo "Starting sqlite server in folder"
        silent: true
      - task: build_sqlite
      - cmd: ./bin/sqlite

  start_client:
    desc: Starts client
    cmds:
      - cmd: echo "Starting client"
        silent: true
      - task: build_client
      - cmd: ./bin/client
