# this workflow will run all pull requests,
# apart from PRs that only change files in manager folder.
on:
  pull_request:
    paths-ignore:
      - 'resources/**'

name: "golangci-lint"
jobs:
  # run golangci-lint to lint the golang source code.
  # the configuration is at /.golangci.yml.
  linter:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          only-new-issues: true
